/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./modules/user/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./modules/user/components/layout/AppHeader.vue')['default']
    BrandStory: typeof import('./modules/user/components/home/BrandStory.vue')['default']
    FeaturedProducts: typeof import('./modules/user/components/home/FeaturedProducts.vue')['default']
    HeroBanner: typeof import('./modules/user/components/home/HeroBanner.vue')['default']
    InstagramIcon: typeof import('./modules/user/components/icons/InstagramIcon.vue')['default']
    LoginModal: typeof import('./modules/user/components/auth/LoginModal.vue')['default']
    ProductCard: typeof import('./modules/user/components/products/ProductCard.vue')['default']
    ProductCategories: typeof import('./modules/user/components/home/ProductCategories.vue')['default']
    RegisterModal: typeof import('./modules/user/components/auth/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./modules/user/components/icons/SearchIcon.vue')['default']
    ShoppingCartIcon: typeof import('./modules/user/components/icons/ShoppingCartIcon.vue')['default']
    StarIcon: typeof import('./modules/user/components/icons/StarIcon.vue')['default']
    UserIcon: typeof import('./modules/user/components/icons/UserIcon.vue')['default']
    WechatIcon: typeof import('./modules/user/components/icons/WechatIcon.vue')['default']
    WeiboIcon: typeof import('./modules/user/components/icons/WeiboIcon.vue')['default']
  }
}
